# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_a', models.TextField()),
                ('document_b', models.TextField()),
                ('result', models.FloatField()),
            ],
        ),
    ]
